apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: goodcheckout
        uses: cloudbees-io/checkout@v1
      - name: wrongcheckout
        with:
          a: value
        uses: actions/checkout@v4
